name: 'Cloud Build'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  serviceName:
    description: 'Name of image to push'
    required: true
  gcloudProjectId:
    description: 'Google Cloud project ID'
    required: true
  gcloudServiceAccount:
    description: 'Email of Google Cloud service account'
    required: true
